name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Installare Eigen
        run: |
          sudo apt update
          sudo apt install -y libeigen3-dev
          echo "Eigen installato"

      - name: Install Python and dependencies
        run: |
          sudo apt install -y python3 python3-pip
          pip3 install numpy matplotlib

      - name: Get Eigen Path
        run: |
          EIGEN_PATH=$(dpkg -L libeigen3-dev | grep "Eigen/Core" | sed 's:/Eigen/Core::' | head -n 1)
          echo "EIGEN_PATH=$EIGEN_PATH" >> $GITHUB_ENV

      - name: Run copilot.py with Eigen path
        run: echo "$EIGEN_PATH" | python copilot.py change_path

      - name: Creare la cartella build
        run: mkdir -p build

      - name: Compilare il codice
        run: |
          g++ -Wall -O3 -std=c++17 -fopenmp -I/usr/include/eigen3 main.cpp -o build/main
        continue-on-error: true
        
      - name: Verificare la presenza dell'eseguibile
        run: ls -l build/

      - name: Testare l'eseguibile
        run: ./build/main 0.001 0 0 100
