name: C++ Build & Test (macOS)

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Installare Eigen
        run: |
          brew install eigen
          echo "Eigen installato"

      - name: Controllare la posizione di Eigen
        run: |
          echo "Contenuto di /opt/homebrew/include/eigen3:"
          ls -l /opt/homebrew/include/eigen3

      - name: Creare la cartella build
        run: mkdir -p build

      - name: Compilare il codice
        run: |
          g++ -Wall -O3 -std=c++17 -fopenmp -I/opt/homebrew/include/eigen3 main.cpp -o build/main
        continue-on-error: true

      - name: Verificare la presenza dell'eseguibile
        run: ls -l build/

      - name: Testare l'eseguibile
        run: ./build/main 0.001 0 0 1000
