name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Installare Eigen
        run: |
          brew update
          brew install eigen
          echo "Eigen installato"

      - name: Install Python and dependencies
        run: |
          python3 -m venv myenv
          source myenv/bin/activate
          pip install numpy
          pip install matplotlib 
          pip install loguru
          pip install customtkinter
          

      - name: Get Eigen Path
        run: |
          EIGEN_PATH=$(brew --prefix eigen)
          echo "EIGEN_PATH=$EIGEN_PATH" >> $GITHUB_ENV

      - name: Run copilot.py with Eigen path
        run:
            source myenv/bin/activate 
            echo "$EIGEN_PATH/Eigen/Dense" | python3 copilot.py change_path

      - name: Creare la cartella build
        run: mkdir -p build

      - name: Compilare il codice
        run: |
          g++ -Wall -O3 -std=c++17 -fopenmp -I$EIGEN_PATH main.cpp -o build/main
        continue-on-error: true
        
      - name: Verificare la presenza dell'eseguibile
        run: ls -l build/

      - name: Testare l'eseguibile
        run: ./build/main 0.001 0 0 100
