name: Windows

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Installare Eigen
        run: |
          choco install eigen
          echo "Eigen installato"

      - name: Install Python and dependencies
        run: |
          choco install python
          pip install numpy matplotlib
          pip install loguru customtkinter
          pip install tk  # Aggiungi questa riga per installare Tkinter

      - name: Get Eigen Path
        run: |
          $EIGEN_PATH = "C:\Program Files\Eigen"
          echo "EIGEN_PATH=$EIGEN_PATH" >> $env:GITHUB_ENV

      - name: Run copilot.py with Eigen path
        run: |
          echo "Running copilot.py with Eigen path"
          python copilot.py change_path "$EIGEN_PATH\\Eigen\\Dense"

      - name: Creare la cartella build
        run: mkdir build

      - name: Compilare il codice
        run: |
          g++ -Wall -O3 -std=c++17 -fopenmp -I"$EIGEN_PATH\Eigen" main.cpp -o build\main.exe
        continue-on-error: true
        
      - name: Verificare la presenza dell'eseguibile
        run: dir build\

      - name: Testare l'eseguibile
        run: build\main.exe 0.001 0 0 100
