name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Installare Eigen
        run: |
          choco install eigen
          echo "Eigen installato"

      - name: Controllare la posizione di Eigen
        run: |
          echo "Contenuto di C:\ProgramData\chocolatey\lib\eigen\tools:"
          dir C:\ProgramData\chocolatey\lib\eigen\tools

      - name: Creare la cartella build
        run: mkdir build

      - name: Compilare il codice
        run: |
          g++ -Wall -O3 -std=c++17 -fopenmp -I"C:\ProgramData\chocolatey\lib\eigen\tools" main.cpp -o build\main.exe
        continue-on-error: true

      - name: Verificare la presenza dell'eseguibile
        run: dir build\

      - name: Testare l'eseguibile
        run: build\main.exe 0.001 0 0 1000
